Rails/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/store', to: 'store#index', as: 'store_base'

end

Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

Rails/app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @data = {'name' => 'teste', 'price' => '10', 'available_quantity' => 10, 'identifier_code' => 'teasgas'}
    @test = Products::ProductPostingCommand.new(@data)
    @test.test
  end
end

Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/app/views/home/_footer.html.erb
<footer>
  <ul>
    <li><a href="">A Domme</a></li>
    <li><a href="">Blog</a></li>
    <li><a href="">Domme Club</a></li>
    <li><a href="">Newsletter</a></li>
    <li><a href="">Contato</a></li>
    <li><a href="">Mídias</a></li>
  </ul>
  <span class="copyright">Domme 2014, Todos os direitos reservados.</span>
</footer>

Rails/app/views/home/_main_menu.html.erb
<header>
    <section class="menu">
      <div class="menu-button">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </section>
    <div class="logo">Domme</div>
</header>
<ul class="menu-options">
  <li><a href="">Loja</a></li>
  <li><a href="">Conheça a Coleção</a></li>
  <li><a href="">Domme Club</a></li>
  <li><a href="">Blog</a></li>
  <li><a href="">A Domme</a></li>
  <li><a href="">Newsletter</a></li>
  <li><a href="">Contato</a></li>
  <li><a href="">Mídias</a></li>
</ul>

Rails/app/views/home/index.html.erb
<div class="photo-layer"></div>
<div id="carousel" class="owl-carousel main-collection">
  <div class="item"><span style="background-image: url('<%= image_path("teste-image.jpg") %>')"></span></div>
  <div class="item"><span style="background-image: url('<%= image_path("home-banner.jpg") %>')"></span></div>
</div>
<div class="actions">
  <button> Conheça a nova coleção</button>
  <%= link_to 'Store', store_base_path %>
</div>

Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Domme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'home/main_menu' %>
    <%= yield %>
    <%= render 'home/footer' %>
</body>
</html>

Rails/app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'store/main_menu' %>
<%= yield %>
<%= render 'store/footer' %>
</body>
</html>

Rails/app/views/store/_footer.html.erb
<footer>
  <span class="copyright">Domme 2014, Todos os direitos reservados.</span>
</footer>

Rails/app/views/store/_main_menu.html.erb
<header>
    <div class="logo">Domme</div>
    <section class="menu">
    </section>
</header>

Rails/app/views/store/index.html.erb
<div id="carousel" class="owl-carousel main-collection">
  <div class="item"><span style="background-image: url('<%= image_path("model.jpg") %>')"></span></div>
</div>

<section class="store-items">
  <div class="store-item">
    <%= image_tag("model2.png"); %>
  </div>
</section>

Rails/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Rails/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Rails/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Rails/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>